// AUTO-GENERATED by scripts/gen_sb_anf_verilog.py - do not hand-edit.
// Functional clone of S0; XOR/AND structure from ANF (not theory-optimal STR).
module SB_ANF (
    input  wire [5:0] x,
    output wire [5:0] y
);

wire m_01 = x[0];
wire m_02 = x[1];
wire m_03 = x[0] & x[1];
wire m_04 = x[2];
wire m_05 = x[0] & x[2];
wire m_06 = x[1] & x[2];
wire m_08 = x[3];
wire m_09 = x[0] & x[3];
wire m_0a = x[1] & x[3];
wire m_0b = x[0] & x[1] & x[3];
wire m_0c = x[2] & x[3];
wire m_0d = x[0] & x[2] & x[3];
wire m_0e = x[1] & x[2] & x[3];
wire m_0f = x[0] & x[1] & x[2] & x[3];
wire m_10 = x[4];
wire m_11 = x[0] & x[4];
wire m_12 = x[1] & x[4];
wire m_13 = x[0] & x[1] & x[4];
wire m_14 = x[2] & x[4];
wire m_15 = x[0] & x[2] & x[4];
wire m_17 = x[0] & x[1] & x[2] & x[4];
wire m_18 = x[3] & x[4];
wire m_19 = x[0] & x[3] & x[4];
wire m_1a = x[1] & x[3] & x[4];
wire m_1c = x[2] & x[3] & x[4];
wire m_20 = x[5];
wire m_21 = x[0] & x[5];
wire m_22 = x[1] & x[5];
wire m_23 = x[0] & x[1] & x[5];
wire m_24 = x[2] & x[5];
wire m_25 = x[0] & x[2] & x[5];
wire m_26 = x[1] & x[2] & x[5];
wire m_27 = x[0] & x[1] & x[2] & x[5];
wire m_28 = x[3] & x[5];
wire m_29 = x[0] & x[3] & x[5];
wire m_2a = x[1] & x[3] & x[5];
wire m_2c = x[2] & x[3] & x[5];
wire m_30 = x[4] & x[5];
wire m_31 = x[0] & x[4] & x[5];
wire m_32 = x[1] & x[4] & x[5];
wire m_34 = x[2] & x[4] & x[5];

assign y[0] = m_03 ^ m_04 ^ m_05 ^ m_08 ^ m_0c ^ m_10 ^ m_11 ^ m_12 ^ m_17 ^ m_1a ^ m_20 ^ m_23 ^ m_26 ^ m_28 ^ m_29 ^ m_30 ^ m_31 ^ m_34;
assign y[1] = m_01 ^ m_03 ^ m_04 ^ m_05 ^ m_06 ^ m_0d ^ m_10 ^ m_14 ^ m_15 ^ m_18 ^ m_1a ^ m_1c ^ m_20 ^ m_21 ^ m_22 ^ m_23 ^ m_25 ^ m_27 ^ m_29 ^ m_2a ^ m_2c ^ m_30 ^ m_34;
assign y[2] = m_01 ^ m_04 ^ m_0a ^ m_0b ^ m_0c ^ m_0e ^ m_13 ^ m_14 ^ m_15 ^ m_18 ^ m_20;
assign y[3] = m_03 ^ m_04 ^ m_05 ^ m_06 ^ m_08 ^ m_0d ^ m_10 ^ m_11 ^ m_12 ^ m_14 ^ m_18 ^ m_1a ^ m_1c ^ m_21 ^ m_24 ^ m_25 ^ m_26 ^ m_27 ^ m_29 ^ m_2a ^ m_2c ^ m_34;
assign y[4] = m_01 ^ m_02 ^ m_08 ^ m_09 ^ m_0b ^ m_0c ^ m_0d ^ m_0e ^ m_10 ^ m_13 ^ m_14 ^ m_15 ^ m_18 ^ m_23 ^ m_24 ^ m_25 ^ m_28;
assign y[5] = m_01 ^ m_02 ^ m_05 ^ m_0b ^ m_0f ^ m_10 ^ m_11 ^ m_13 ^ m_14 ^ m_15 ^ m_17 ^ m_19 ^ m_1a ^ m_1c ^ m_20 ^ m_23 ^ m_24 ^ m_26 ^ m_29 ^ m_2a ^ m_32 ^ m_34;

endmodule
