// AUTO-GENERATED by scripts/gen_lut_verilog.py — do not hand-edit.
// Regenerate: python scripts/gen_lut_verilog.py
// 6-bit APN S-box S0 (Dillon); interface per 2026 赛题二.
module SB (
    input  wire [5:0] x,
    output reg  [5:0] y
);
    always @* begin
        case (x)
            6'd0 : y = 6'h00;
            6'd1 : y = 6'h36;
            6'd2 : y = 6'h30;
            6'd3 : y = 6'h0d;
            6'd4 : y = 6'h0f;
            6'd5 : y = 6'h12;
            6'd6 : y = 6'h35;
            6'd7 : y = 6'h23;
            6'd8 : y = 6'h19;
            6'd9 : y = 6'h3f;
            6'd10: y = 6'h2d;
            6'd11: y = 6'h34;
            6'd12: y = 6'h03;
            6'd13: y = 6'h14;
            6'd14: y = 6'h29;
            6'd15: y = 6'h21;
            6'd16: y = 6'h3b;
            6'd17: y = 6'h24;
            6'd18: y = 6'h02;
            6'd19: y = 6'h22;
            6'd20: y = 6'h0a;
            6'd21: y = 6'h08;
            6'd22: y = 6'h39;
            6'd23: y = 6'h25;
            6'd24: y = 6'h3c;
            6'd25: y = 6'h13;
            6'd26: y = 6'h2a;
            6'd27: y = 6'h0e;
            6'd28: y = 6'h32;
            6'd29: y = 6'h1a;
            6'd30: y = 6'h3a;
            6'd31: y = 6'h18;
            6'd32: y = 6'h27;
            6'd33: y = 6'h1b;
            6'd34: y = 6'h15;
            6'd35: y = 6'h11;
            6'd36: y = 6'h10;
            6'd37: y = 6'h1d;
            6'd38: y = 6'h01;
            6'd39: y = 6'h3e;
            6'd40: y = 6'h2f;
            6'd41: y = 6'h28;
            6'd42: y = 6'h33;
            6'd43: y = 6'h38;
            6'd44: y = 6'h07;
            6'd45: y = 6'h2b;
            6'd46: y = 6'h2c;
            6'd47: y = 6'h26;
            6'd48: y = 6'h1f;
            6'd49: y = 6'h0b;
            6'd50: y = 6'h04;
            6'd51: y = 6'h1c;
            6'd52: y = 6'h3d;
            6'd53: y = 6'h2e;
            6'd54: y = 6'h05;
            6'd55: y = 6'h31;
            6'd56: y = 6'h09;
            6'd57: y = 6'h06;
            6'd58: y = 6'h17;
            6'd59: y = 6'h20;
            6'd60: y = 6'h1e;
            6'd61: y = 6'h0c;
            6'd62: y = 6'h37;
            6'd63: y = 6'h16;
            default: y = 6'h00;
        endcase
    end
endmodule
