"""Generate rtl/sb_lut_baseline.v from truth_table (single source of truth)."""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))

from truth_table import table_64  # noqa: E402

HEADER = """// AUTO-GENERATED by scripts/gen_lut_verilog.py — do not hand-edit.
// Regenerate: python scripts/gen_lut_verilog.py
// 6-bit APN S-box S0 (Dillon); interface per 2026 赛题二.
module SB (
    input  wire [5:0] x,
    output reg  [5:0] y
);
    always @* begin
        case (x)
"""


def main() -> int:
    t = table_64()
    lines = [HEADER]
    for i, v in enumerate(t):
        sep = "" if i >= 10 else " "
        lines.append(f"            6'd{i}{sep}: y = 6'h{v:02x};\n")
    lines.append(
        """            default: y = 6'h00;
        endcase
    end
endmodule
"""
    )
    out = ROOT / "rtl" / "sb_lut_baseline.v"
    out.write_text("".join(lines), encoding="utf-8", newline="\n")
    print(f"Wrote {out} ({len(t)} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
