"""
Emit rtl/sb_anf_rtl.v: module SB_ANF — purely combinational ANF of S0 (six coordinates).

This is a concrete candidate RTL (XOR/AND heavy); map with Yosys+NanGate for D_STA.
Optional hand-in still needs STR against contest Table-2 naming for theory scoring.

Run from scripts/:  python gen_sb_anf_verilog.py
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RTL = ROOT / "rtl" / "sb_anf_rtl.v"

sys.path.insert(0, str(Path(__file__).resolve().parent))
from coords_anf import mobius_anf_6var  # noqa: E402
from truth_table import coord_truth  # noqa: E402


def eval_anf(coeffs: list[int], w: int) -> int:
    acc = 0
    for mask in range(64):
        if not coeffs[mask]:
            continue
        prod = 1
        for i in range(6):
            if mask & (1 << i):
                prod &= (w >> i) & 1
        acc ^= prod
    return acc & 1


def main() -> int:
    masks_needed: set[int] = set()
    coeff_per_k: list[list[int]] = []
    for k in range(6):
        c = mobius_anf_6var(coord_truth(k))
        coeff_per_k.append(c)
        for m in range(64):
            if c[m]:
                masks_needed.add(m)
        for w in range(64):
            assert eval_anf(c, w) == coord_truth(k)[w], (k, w)

    lines = [
        "// AUTO-GENERATED by scripts/gen_sb_anf_verilog.py - do not hand-edit.",
        "// Functional clone of S0; XOR/AND structure from ANF (not theory-optimal STR).",
        "module SB_ANF (",
        "    input  wire [5:0] x,",
        "    output wire [5:0] y",
        ");",
        "",
    ]

    for mask in sorted(masks_needed):
        name = f"m_{mask:02x}"
        idxs = [i for i in range(6) if mask & (1 << i)]
        if mask == 0:
            lines.append(f"wire {name} = 1'b1;")
        elif len(idxs) == 1:
            lines.append(f"wire {name} = x[{idxs[0]}];")
        else:
            lines.append(f"wire {name} = " + " & ".join(f"x[{i}]" for i in idxs) + ";")

    lines.append("")
    for k in range(6):
        c = coeff_per_k[k]
        terms = [m for m in range(64) if c[m]]
        if not terms:
            lines.append(f"assign y[{k}] = 1'b0;")
        else:
            rhs = " ^ ".join(f"m_{m:02x}" for m in terms)
            lines.append(f"assign y[{k}] = {rhs};")

    lines.extend(["", "endmodule", ""])
    RTL.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"Wrote {RTL}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
